#!/bin/bash

PKG=
PKG_LST='/var/lib/pkgutils/packages'
ROOT='/'
DRYRUN=
RECURS=

while [ $# -gt 0 ]; do
	case $1 in
		--warn | -n    ) DRYRUN=1; shift; break;;
		--recurse | -r ) RECURS=1; shift; break;;
		*           ) break;;
    esac
done
PKG=$1
FILE=${PKG%%tar*}
FILE=${FILE##*/}

# untar package
if [ $DRYRUN ]; then
	echo "tar xvf $PKG -C /"
else
	tar xvf $PKG -C /
fi

# write out file listing
if [ $DRYRUN ]; then
	echo "tar tvf $PKG > $PKG_LST/$FILE"
else
	tar tvf $PKG > $PKG_LST/$FILE 
fi
